Feature/manage program
PilotCityInc/pcv4maxpro pull request #18
Opened 2020-09-07 07:58 UTC by prajit20

Pulled all the pages related to manage dashboards into the feature/manage-program branch. Added the Sidebar to all the pages. Might nee dot be reviewed for responsiveness? Still need to work on the storybook. Ran lint and unit test and it all worked.

2020-09-07 19:27 UTC, Juxsta requested changes

2020-09-07 19:27 UTC, Juxsta commented on src/views/ManageProgram/components/Nav.vue
> +    const endDate = ref('DAY, MON 1');
Turn this into a prop

2020-09-07 19:27 UTC, Juxsta commented on src/views/ManageProgram/components/Nav.vue
> +    const items = ref([
Put this in a separate file and import them.
Put this into a const.ts file and rename the variable to reflect that your importing a constant

2020-09-07 19:27 UTC, Juxsta commented on src/views/ManageProgram/components/Nav.vue
> +    const activeTab = ref({ title: 'Detail', color: 'purple' });
use an array reference. Unnecessary value duplication here. 
use items.value[0] for example

2020-09-07 19:27 UTC, Juxsta commented on src/views/ManageProgram/routes.ts
> +    component: Nav
Remove this, or you can inject the route only in development. We don't want to expose these routes in production

2020-09-07 19:27 UTC, Juxsta commented on src/views/ManageProgram/views/ManageStakeholder.vue
> +    });
clean up this code. Move constant values to its own file. 
Add a typescript casting function to inject id's rather than declaring the id's beforehand.

2020-09-07 19:27 UTC, Juxsta commented on src/views/ManageProgram/views/ManageStakeholder.vue
> +    ]);
If these aren't changed move them to their own file. It also seems that the width property is redundant. just use 10% directly in the html

2020-09-07 19:27 UTC, Juxsta commented on src/views/ManageProgram/views/Participants.vue
> +    function indexHandler(
This is the same as ManageStakeHolder.vue
Never copy and paste code.
Create a new component and import it here. Seems like u need a table component wrapper

2020-09-07 19:29 UTC, Juxsta reviewed
You reused code way too often. You newed to create wrapper component or a mixin, or a factory so that u can reuse the code.

2020-09-07 19:37 UTC, jinocenc commented on src/views/ManageProgram/routes.ts
> +    component: Nav
What's wrong with these routes?

2020-09-07 19:39 UTC, jinocenc commented on src/views/ManageProgram/views/ManageStakeholder.vue
> +    ]);
The width is part of the data table lol

2020-09-08 00:02 UTC, jinocenc requested changes
html good, same changes mentioned

2020-09-08 19:35 UTC, prajit20 commented on src/views/ManageProgram/views/Participants.vue
> +    function indexHandler(
Ok, I will do that. This was the initial code and then ManageStakeholder copied this same code from here

2020-09-10 04:11 UTC, prajit20 commented on src/views/ManageProgram/components/Nav.vue
> +    const items = ref([
i already resolved the issues

2020-09-10 04:24 UTC, Juxsta commented
Write a storybook for your IndexedTable Component too

2020-09-10 04:30 UTC, Juxsta commented
#19 Review and merge this fix

2020-09-10 04:44 UTC, Juxsta commented on src/views/ManageProgram/components/Nav.vue
> +    const items = ref([
You can move items out since you never use it

2020-09-10 04:45 UTC, Juxsta commented on src/views/ManageProgram/components/Nav.vue
> +    const items = ref([
Items is constant. It doesn't change so it should be moved to a const file

2020-09-10 04:47 UTC, Juxsta commented on src/views/ManageProgram/components/Nav.vue
> +    const activeTab = ref({ title: 'Detail', color: 'purple' });
Ur duplicating the value of an item here. You should use ref(items.value[0])

2020-09-10 04:51 UTC, Juxsta commented on src/views/ManageProgram/routes.ts
> +    component: Nav
This isn't a real page so it shouldn't be available in production. You can keep it in development though. Check this @jinocenc @prajit20 #19

2020-09-10 06:35 UTC, prajit20 commented on src/views/ManageProgram/components/Nav.vue
> +    const activeTab = ref({ title: 'Detail', color: 'purple' });
I am not able to do it as it has to be item.values and my whole page broke. when i import from const.ts file

2020-11-04 04:08 UTC, closed without merging